language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - sudo locale-gen de_DE.UTF-8 es_ES.UTF-8 en_GB.UTF-8 en_US.UTF-8 fr_FR.UTF-8 it_IT.UTF-8 pl_PL.UTF-8 ru_RU.UTF-8
  - composer global require hirak/prestissimo

install:
- travis_wait 30 composer install

script:
  - php ./vendor/bin/phpunit
