language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - sudo apt-get install locales
  - sudo sed -i 's/^# de_DE/de_DE/g;' /etc/locale.gen
  - sudo sed -i 's/^# es_ES/es_ES/g;' /etc/locale.gen
  - sudo sed -i 's/^# en_GB/en_GB/g;' /etc/locale.gen
  - sudo sed -i 's/^# en_US/en_US/g;' /etc/locale.gen
  - sudo sed -i 's/^# fr_FR/fr_FR/g;' /etc/locale.gen
  - sudo sed -i 's/^# it_IT/it_IT/g;' /etc/locale.gen
  - sudo sed -i 's/^# pl_PL/pl_PL/g;' /etc/locale.gen
  - sudo sed -i 's/^# ru_RU/ru_RU/g;' /etc/locale.gen
  - sudo locale-gen

install:
  - composer install

script:
  - php ./vendor/bin/phpunit
