language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - sudo apt-get install locales
  - sed -i 's/^# de_DE/de_DE/g; \
            s/^# es_ES/es_ES/g; \
            s/^# en_GB/en_GB/g; \
            s/^# en_US/en_US/g; \
            s/^# fr_FR/fr_FR/g; \
            s/^# it_IT/it_IT/g; \
            s/^# pl_PL/pl_PL/g; \
            s/^# ru_RU/ru_RU/g;' /etc/locale.gen \
    && locale-gen

install:
  - composer install

script:
  - php ./vendor/bin/phpunit
