version: '3'

services:
    #
    # Required to run project
    #
    php:
        image: meritoo/php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-php
        entrypoint: php
        command: -S 0.0.0.0:9999
        environment:
            PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE}
        volumes:
            - .:/var/www/application:cached
    composer:
        image: meritoo/php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-composer
        entrypoint: php -d memory_limit=-1 /usr/local/bin/composer
        volumes:
            - .:/var/www/application:cached
    #
    # Required to run PHPUnit's tests
    #
    phpunit:
        image: meritoo/php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-phpunit
        entrypoint: ./vendor/bin/phpunit
        command: --version
        volumes:
            - .:/var/www/application:cached
        environment:
            XDEBUG_MODE: coverage
