version: '3'

services:
    php-cli:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php-cli
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-php-cli
        working_dir: /project
        entrypoint: php
        command: -S 0.0.0.0:9999
        build:
            context: ./.docker/config
            args:
                - TIMEZONE=$TIMEZONE
        volumes:
            - .:/project
    composer:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php-cli
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-composer
        working_dir: /project
        command: composer
        volumes:
            - .:/project
