version: '3'

services:
    #
    # Required to run project
    #
    php:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-php
        entrypoint: php
        command: -S 0.0.0.0:9999
        build:
            context: ./docker/config
            args:
                - TIMEZONE=${TIMEZONE}
        volumes:
            - .:/project:cached
    composer:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-composer
        entrypoint: php -d memory_limit=-1 /usr/local/bin/composer
        volumes:
            - .:/project:cached
    #
    # Required to run PHPUnit's tests
    #
    phpunit:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-phpunit
        entrypoint: ./vendor/bin/phpunit
        command: --version
        volumes:
            - .:/project:cached
