version: '3'

services:
    php:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-php
        entrypoint: php
        command: -S 0.0.0.0:9999
        build:
            context: ./docker/config
            args:
                - TIMEZONE=${TIMEZONE}
        volumes:
            - .:/project:cached
    composer:
        image: ${DOCKER_CONTAINER_OWNER}/${DOCKER_CONTAINER_PROJECT}-php
        container_name: ${DOCKER_CONTAINER_OWNER}-${DOCKER_CONTAINER_PROJECT}-composer
        entrypoint: composer
        volumes:
            - .:/project:cached
