name: Verify stability
run-name: ${{ github.actor }} is verifying stability
on: [ push ]
#on:
#    push:
#        branches: [ master, develop ]
#    pull_request:
#        branches: [ master, develop ]
permissions:
    contents: read
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ '8.0', '8.1', '8.2' ]
        steps:
            -   name: Hello
                run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: dom, fileinfo, intl-72.1, json, pcre, simplexml
            -   name: Install locales
                run: |
                    sudo apt-get update \
                    && sudo apt-get install -y --no-install-recommends --fix-missing \
                        locales
            -   name: Generate locales
                run: |
                    sudo sed -i "s/^# de_DE/de_DE/g; \
                        s/^# es_ES/es_ES/g; \
                        s/^# en_GB/en_GB/g; \
                        s/^# en_US/en_US/g; \
                        s/^# fr_FR/fr_FR/g; \
                        s/^# it_IT/it_IT/g; \
                        s/^# pl_PL/pl_PL/g; \
                        s/^# ru_RU/ru_RU/g;" /etc/locale.gen \
                    && sudo locale-gen
            -   name: Checkout branch
                uses: actions/checkout@v3
            -   name: Validate composer.json and composer.lock
                run: composer validate --strict
            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-
            -   name: Install Composer dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --no-plugins --prefer-dist
            -   name: Run PHPUnit tests
                run: vendor/bin/phpunit --no-coverage
            -   name: Bye 👋
                run: echo "🍏 This job's status is ${{ job.status }}."
